name:  dsci522-dockerfile-practice-env
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.2.2
  - pandera=0.20.4
  - python=3.11
  - matplotlib=3.6.2
  - numpy=1.23.5
  - pip
  - pip:
      - deepchecks==0.18.1

